"""Contrat Intent v1 : la couche d'intention d'une infrastructure (épingles, couleurs, groupes, annotations,
connecteurs), quatrième contrat du paquet."""

from ld_contracts.intent.annotations import (
    ANNOTATION_KINDS,
    DEFAULT_ANNOTATION_SIZE,
    DEFAULT_ANNOTATION_STYLE,
    MAX_ANNOTATIONS,
    Anchor,
    Annotation,
    AnnotationStyle,
    ImageContent,
    Merge,
    NoteContent,
    ShapeContent,
    TableContent,
    default_size,
)
from ld_contracts.intent.connectors import (
    DEFAULT_CONNECTOR_STYLE,
    DEFAULT_HEADS,
    MAX_CONNECTORS,
    AttachedEnd,
    Connector,
    ConnectorStyle,
    FreeEnd,
    Heads,
    Side,
)
from ld_contracts.intent.intent import (
    DEFAULT_GROUP_STYLE,
    INTENT_MAJOR,
    INTENT_VERSION,
    MAX_GROUPS,
    MAX_PINS,
    DeviceColor,
    Group,
    GroupStyle,
    Hue,
    Intent,
    Pin,
    TypeColor,
    empty_intent,
    upgraded,
)

__all__ = [
    "ANNOTATION_KINDS",
    "DEFAULT_ANNOTATION_SIZE",
    "DEFAULT_ANNOTATION_STYLE",
    "DEFAULT_CONNECTOR_STYLE",
    "DEFAULT_GROUP_STYLE",
    "DEFAULT_HEADS",
    "INTENT_MAJOR",
    "INTENT_VERSION",
    "MAX_ANNOTATIONS",
    "MAX_CONNECTORS",
    "MAX_GROUPS",
    "MAX_PINS",
    "Anchor",
    "Annotation",
    "AnnotationStyle",
    "AttachedEnd",
    "Connector",
    "ConnectorStyle",
    "DeviceColor",
    "FreeEnd",
    "Group",
    "GroupStyle",
    "Heads",
    "Side",
    "Hue",
    "ImageContent",
    "Intent",
    "Merge",
    "NoteContent",
    "Pin",
    "ShapeContent",
    "TableContent",
    "TypeColor",
    "default_size",
    "empty_intent",
    "upgraded",
]
